### ISSUE TITLE
E4PreferenceRegistry force preference scope to be the same as the preferencePage plugin

### ISSUE THREAD

**Issue by seblatre** [opcoach/e4Preferences#1]
The E4PreferenceRegistry prevents a preference page to define its own PreferenceScope which could be different from the plugin in which preferencePage is defined.

In my example, preferences are defined in a service layer and displayed in UI layer through preference page.
The page define its own preference scope but E4PreferenceRegistry overwrite it to an unwanted value.

``` java
if (page instanceof FieldEditorPreferencePage)
{
    IPreferenceStore store = new ScopedPreferenceStore(InstanceScope.INSTANCE, bundleId);
    ((FieldEditorPreferencePage) page).setPreferenceStore(store);
}
```

**Comment by opcoach** [comment]
This is done with IStoreProviders (can close it !)
