### ISSUE TITLE
Schema declarations not included in artifact

### ISSUE THREAD

**Issue by MatFl** [opcoach/e4Preferences#7]
The extension point schema exsd files are not included in the deployed jar in the p2 repository. The folder needs to be added to `bin.includes` in the `build.properties` file.

**Comment by opcoach** [comment]
A new version has been released on bintray  : 

https://dl.bintray.com/opcoach/e4Preferences
(new version with xml schemas for extension points : e4 Preferences 1.0.0.201603301113)
